services:
  sandbox-dev:
    build:
      context: .
      args:
        USERNAME: ${USERNAME:-dev}
      secrets:
        - user_password
    container_name: sandbox-dev
    ports:
      - "2222:22"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

secrets:
  user_password:
    file: ${PASSWORD_FILE:-./.secrets/dev_password.txt}
